import type { ResumeData } from "./resume-data";

export const DUMMY_DATA_DISCLAIMER =
    "The below content was generated by ChatGPT for demonstration purposes. Any similarities to real people are purely coincidental.";

const dummy_resume_data: ResumeData[] = [
    {
        name: "John Doe",
        title: "Senior Software Engineer",
        phone: "(555) 555-5555",
        email: "john.doe@example.com",
        location: "Austin, TX",
        summary: (
            <>
                Experienced full-stack software engineer with expertise in web
                development, cloud solutions, and scalable applications.
                Proficient in modern frameworks and tools, with a passion for
                building innovative and efficient systems.
            </>
        ),
        education: [
            {
                start: "Sep 2010",
                end: "Jun 2014",
                level: "Bachelor's Degree",
                field: "Computer Science",
                subfield: "Software Engineering",
                school: {
                    name: "University of Texas",
                    location: "Austin, TX",
                },
            },
        ],
        certifications: [
            {
                date: "Mar 2020",
                name: "AWS Certified Solutions Architect",
            },
            {
                date: "Jul 2021",
                name: "Certified Kubernetes Administrator",
            },
        ],
        skills: [
            { name: "JavaScript", level: "expert" },
            { name: "React", level: "expert" },
            { name: "TypeScript", level: "experienced" },
            { name: "Node.js", level: "experienced" },
            { name: "AWS", level: "skillful" },
            "HTML",
            "CSS",
            "Docker",
            "Kubernetes",
            "Git",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "Spanish", level: "B2" },
        ],
        links: [
            {
                url: "https://github.com/johndoe",
                prettyUrl: "github.com/johndoe",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/john-doe",
                prettyUrl: "linkedin.com/in/john-doe",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "TechCorp Inc.",
                location: "San Francisco, CA",
                positions: [
                    {
                        title: "Senior Software Engineer",
                        start: "Jan 2020",
                        end: "Present",
                        points: [
                            <>
                                Led the development of a scalable microservices
                                architecture using{" "}
                                <span className="skill">Node.js</span> and{" "}
                                <span className="skill">AWS</span>.
                            </>,
                            <>
                                Improved performance of web applications by 20%
                                through optimizations in{" "}
                                <span className="skill">React</span> and{" "}
                                <span className="skill">TypeScript</span>.
                            </>,
                            <>
                                Mentored junior engineers and conducted code
                                reviews.
                            </>,
                        ],
                        skills: [
                            "JavaScript",
                            "Node.js",
                            "AWS",
                            "React",
                            "TypeScript",
                        ],
                    },
                ],
            },
            {
                organization: "Web Solutions LLC",
                location: "Austin, TX",
                positions: [
                    {
                        title: "Software Engineer",
                        start: "Jun 2016",
                        end: "Dec 2019",
                        points: [
                            <>
                                Developed and maintained client-facing web
                                applications using{" "}
                                <span className="skill">React</span> and{" "}
                                <span className="skill">Node.js</span>.
                            </>,
                            <>
                                Collaborated with cross-functional teams to
                                design, build, and deploy scalable web services.
                            </>,
                            <>
                                Integrated third-party APIs and improved UX/UI
                                performance.
                            </>,
                        ],
                        skills: [
                            "JavaScript",
                            "React",
                            "Node.js",
                            "API Integration",
                        ],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Real-Time Chat Application",
                description: (
                    <>
                        A real-time chat app built with{" "}
                        <span className="skill">WebSocket</span> and{" "}
                        <span className="skill">Node.js</span> for fast
                        client-to-client communication.
                    </>
                ),
                points: [
                    <>
                        Designed the <span className="skill">WebSocket</span>
                        -based architecture for low-latency communication.
                    </>,
                    <>
                        Deployed the application on{" "}
                        <span className="skill">AWS</span> using{" "}
                        <span className="skill">Docker</span> and{" "}
                        <span className="skill">Kubernetes</span>.
                    </>,
                ],
            },
        ],
        references: [
            {
                name: "Laura Thompson",
                company: "Tech Innovations LLC",
                email: "laura.thompson@example.com",
            },
        ],
    },
    {
        name: "Jane Smith",
        title: "Full-Stack Developer",
        phone: "(555) 555-5556",
        email: "jane.smith@example.com",
        location: "New York, NY",
        summary: (
            <>
                Full-stack developer with a deep understanding of both front-end
                and back-end technologies. Experienced in building web
                applications with <span className="skill">React</span> and{" "}
                <span className="skill">Node.js</span>.
            </>
        ),
        education: [
            {
                start: "Sep 2012",
                end: "Jun 2016",
                level: "Bachelor's Degree",
                field: "Information Technology",
                subfield: "Web Development",
                school: {
                    name: "New York University",
                    location: "New York, NY",
                },
            },
        ],
        certifications: [
            {
                date: "Feb 2019",
                name: "Certified Full-Stack Developer",
            },
        ],
        skills: [
            { name: "JavaScript", level: "expert" },
            { name: "React", level: "expert" },
            { name: "Node.js", level: "experienced" },
            "HTML",
            "CSS",
            "MySQL",
            "MongoDB",
            "Docker",
            "Git",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "French", level: "B1" },
        ],
        links: [
            {
                url: "https://github.com/janesmith",
                prettyUrl: "github.com/janesmith",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/jane-smith",
                prettyUrl: "linkedin.com/in/jane-smith",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "AppDev Solutions",
                location: "New York, NY",
                positions: [
                    {
                        title: "Full-Stack Developer",
                        start: "Jan 2017",
                        end: "Present",
                        points: [
                            <>
                                Developed and deployed full-stack web
                                applications using{" "}
                                <span className="skill">React</span> and{" "}
                                <span className="skill">Node.js</span>.
                            </>,
                            <>
                                Created dynamic and responsive user interfaces.
                            </>,
                            <>
                                Managed database integrations with{" "}
                                <span className="skill">MongoDB</span> and{" "}
                                <span className="skill">MySQL</span>.
                            </>,
                        ],
                        skills: ["React", "Node.js", "MongoDB", "MySQL"],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "E-Commerce Platform",
                description: (
                    <>
                        Developed a full-fledged e-commerce platform with{" "}
                        <span className="skill">React</span> on the front-end
                        and <span className="skill">Node.js</span> on the
                        back-end.
                    </>
                ),
                points: [
                    <>Implemented secure payment gateways.</>,
                    <>Integrated inventory management systems.</>,
                ],
            },
        ],
        references: [
            {
                name: "Michael Johnson",
                company: "Cloud Solutions Inc.",
                email: "michael.johnson@example.com",
            },
        ],
    },
    {
        name: "Alice Johnson",
        title: "Front-End Developer",
        phone: "(555) 555-5557",
        email: "alice.johnson@example.com",
        location: "Seattle, WA",
        summary: (
            <>
                Skilled front-end developer with experience in building modern
                web interfaces using
                <span className="skill">React</span>,{" "}
                <span className="skill">HTML</span>, and{" "}
                <span className="skill">CSS</span>. Passionate about delivering
                intuitive user experiences.
            </>
        ),
        education: [
            {
                start: "Sep 2015",
                end: "Jun 2019",
                level: "Bachelor's Degree",
                field: "Computer Science",
                subfield: "Web Development",
                school: {
                    name: "University of Washington",
                    location: "Seattle, WA",
                },
            },
        ],
        certifications: [
            {
                date: "Apr 2020",
                name: "Certified Front-End Developer",
            },
            {
                date: "Sep 2021",
                name: "JavaScript Specialist",
            },
        ],
        skills: [
            { name: "JavaScript", level: "expert" },
            { name: "React", level: "expert" },
            { name: "HTML", level: "experienced" },
            { name: "CSS", level: "experienced" },
            { name: "Sass", level: "skillful" },
            { name: "Responsive Design", level: "experienced" },
            "Git",
            "Webpack",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "German", level: "B1" },
        ],
        links: [
            {
                url: "https://github.com/alicejohnson",
                prettyUrl: "github.com/alicejohnson",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/alice-johnson",
                prettyUrl: "linkedin.com/in/alice-johnson",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Web Innovations LLC",
                location: "Seattle, WA",
                positions: [
                    {
                        title: "Front-End Developer",
                        start: "Jul 2019",
                        end: "Present",
                        points: [
                            <>
                                Collaborated with UX/UI designers to develop
                                responsive web applications using{" "}
                                <span className="skill">React</span> and{" "}
                                <span className="skill">Redux</span>.
                            </>,
                            <>
                                Implemented unit tests and end-to-end testing
                                using <span className="skill">Jest</span> and{" "}
                                <span className="skill">Cypress</span>.
                            </>,
                            <>
                                Optimized web applications for maximum speed and
                                scalability.
                            </>,
                        ],
                        skills: ["React", "Redux", "JavaScript", "CSS"],
                    },
                ],
            },
            {
                organization: "Creative Solutions",
                location: "Bellevue, WA",
                positions: [
                    {
                        title: "Junior Front-End Developer",
                        start: "Jun 2018",
                        end: "Jun 2019",
                        points: [
                            <>
                                Assisted in the development of user-friendly
                                interfaces for web applications.
                            </>,
                            <>
                                Maintained and updated existing web applications
                                to improve user experience.
                            </>,
                            <>
                                Collaborated with back-end developers to
                                integrate APIs.
                            </>,
                        ],
                        skills: ["HTML", "CSS", "JavaScript"],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Portfolio Website",
                description: (
                    <>
                        Developed a personal portfolio website to showcase my
                        projects using <span className="skill">React</span> and{" "}
                        <span className="skill">Gatsby</span>.
                    </>
                ),
                points: [
                    <>
                        Implemented responsive design to ensure compatibility
                        across devices.
                    </>,
                    <>
                        Integrated a blog section using Markdown for content
                        management.
                    </>,
                ],
            },
            {
                name: "E-Commerce Web App",
                description: (
                    <>
                        Created a full-featured e-commerce web application using{" "}
                        <span className="skill">React</span> and{" "}
                        <span className="skill">Node.js</span>.
                    </>
                ),
                points: [
                    <>
                        Developed shopping cart functionality with real-time
                        updates.
                    </>,
                    <>
                        Integrated payment processing using{" "}
                        <span className="skill">Stripe</span>.
                    </>,
                ],
            },
        ],
        references: [
            {
                name: "Rebecca Wilson",
                company: "Creative Agency Inc.",
                email: "rebecca.wilson@example.com",
            },
        ],
    },
    {
        name: "Robert Green",
        title: "Back-End Developer",
        phone: "(555) 555-5558",
        email: "robert.green@example.com",
        location: "Chicago, IL",
        summary: (
            <>
                Dedicated back-end developer with expertise in{" "}
                <span className="skill">Node.js</span> and
                <span className="skill">SQL</span> databases. Experienced in
                designing and maintaining robust server-side applications.
            </>
        ),
        education: [
            {
                start: "Sep 2011",
                end: "Jun 2015",
                level: "Bachelor's Degree",
                field: "Computer Science",
                subfield: "Software Development",
                school: {
                    name: "University of Illinois",
                    location: "Urbana-Champaign, IL",
                },
            },
        ],
        certifications: [
            {
                date: "May 2018",
                name: "Certified Node.js Developer",
            },
            {
                date: "Aug 2020",
                name: "MongoDB Certified Developer",
            },
        ],
        skills: [
            { name: "Node.js", level: "expert" },
            { name: "Express", level: "experienced" },
            { name: "SQL", level: "experienced" },
            { name: "MongoDB", level: "experienced" },
            { name: "RESTful APIs", level: "skillful" },
            "Git",
            "Docker",
            "GraphQL",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "Spanish", level: "A2" },
        ],
        links: [
            {
                url: "https://github.com/robertgreen",
                prettyUrl: "github.com/robertgreen",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/robert-green",
                prettyUrl: "linkedin.com/in/robert-green",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Tech Solutions Inc.",
                location: "Chicago, IL",
                positions: [
                    {
                        title: "Back-End Developer",
                        start: "Jul 2019",
                        end: "Present",
                        points: [
                            <>
                                Developed and maintained RESTful APIs using{" "}
                                <span className="skill">Node.js</span> and{" "}
                                <span className="skill">Express</span>.
                            </>,
                            <>
                                Implemented data storage solutions using{" "}
                                <span className="skill">MongoDB</span> and{" "}
                                <span className="skill">PostgreSQL</span>.
                            </>,
                            <>
                                Collaborated with front-end developers to
                                integrate user-facing elements.
                            </>,
                        ],
                        skills: ["Node.js", "Express", "MongoDB", "PostgreSQL"],
                    },
                ],
            },
            {
                organization: "Web Development Agency",
                location: "Chicago, IL",
                positions: [
                    {
                        title: "Junior Back-End Developer",
                        start: "Jun 2016",
                        end: "Jun 2019",
                        points: [
                            <>
                                Assisted in the development of server-side logic
                                and databases.
                            </>,
                            <>
                                Wrote reusable, testable, and efficient code in{" "}
                                <span className="skill">JavaScript</span>.
                            </>,
                            <>
                                Participated in code reviews and contributed to
                                improving application performance.
                            </>,
                        ],
                        skills: ["Node.js", "SQL", "JavaScript"],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Inventory Management System",
                description: (
                    <>
                        Designed and developed an inventory management system
                        using <span className="skill">Node.js</span> and{" "}
                        <span className="skill">MongoDB</span>.
                    </>
                ),
                points: [
                    <>
                        Implemented user authentication and role-based access
                        control.
                    </>,
                    <>
                        Optimized database queries to improve application
                        performance.
                    </>,
                ],
            },
            {
                name: "Weather API Service",
                description: (
                    <>
                        Created a weather data service using{" "}
                        <span className="skill">Node.js</span> and{" "}
                        <span className="skill">GraphQL</span>.
                    </>
                ),
                points: [
                    <>
                        Integrated third-party weather data APIs to provide
                        real-time updates.
                    </>,
                    <>Developed comprehensive documentation for API usage.</>,
                ],
            },
        ],
        references: [
            {
                name: "Daniel Smith",
                company: "Mobile Innovations LLC",
                phone: "(555) 555-5567",
            },
        ],
    },
    {
        name: "Emily Davis",
        title: "Full-Stack Developer",
        phone: "(555) 555-5559",
        email: "emily.davis@example.com",
        location: "Denver, CO",
        summary: (
            <>
                Full-stack developer with proficiency in both front-end and
                back-end technologies, including
                <span className="skill">React</span>,{" "}
                <span className="skill">Node.js</span>, and{" "}
                <span className="skill">MongoDB</span>. Passionate about
                developing scalable web applications.
            </>
        ),
        education: [
            {
                start: "Sep 2014",
                end: "Jun 2018",
                level: "Bachelor's Degree",
                field: "Information Technology",
                subfield: "Web Development",
                school: {
                    name: "University of Denver",
                    location: "Denver, CO",
                },
            },
        ],
        certifications: [
            {
                date: "Jan 2020",
                name: "Certified Full-Stack Developer",
            },
            {
                date: "Nov 2021",
                name: "AWS Certified Developer",
            },
        ],
        skills: [
            { name: "JavaScript", level: "expert" },
            { name: "React", level: "expert" },
            { name: "Node.js", level: "experienced" },
            { name: "MongoDB", level: "experienced" },
            { name: "Express", level: "experienced" },
            "HTML",
            "CSS",
            "Git",
            "Docker",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "French", level: "B2" },
        ],
        links: [
            {
                url: "https://github.com/emilydavis",
                prettyUrl: "github.com/emilydavis",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/emily-davis",
                prettyUrl: "linkedin.com/in/emily-davis",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Innovative Solutions LLC",
                location: "Denver, CO",
                positions: [
                    {
                        title: "Full-Stack Developer",
                        start: "Jul 2018",
                        end: "Present",
                        points: [
                            <>
                                Developed web applications using{" "}
                                <span className="skill">React</span> for
                                front-end and{" "}
                                <span className="skill">Node.js</span> for
                                back-end.
                            </>,
                            <>
                                Collaborated with UX/UI designers to implement
                                responsive design.
                            </>,
                            <>
                                Wrote unit tests and performed code reviews to
                                ensure high-quality code.
                            </>,
                        ],
                        skills: ["React", "Node.js", "MongoDB", "Express"],
                    },
                ],
            },
            {
                organization: "Tech Startup Inc.",
                location: "Denver, CO",
                positions: [
                    {
                        title: "Junior Full-Stack Developer",
                        start: "Jan 2017",
                        end: "Jun 2018",
                        points: [
                            <>
                                Assisted in the development of web applications
                                using <span className="skill">JavaScript</span>,{" "}
                                <span className="skill">HTML</span>, and{" "}
                                <span className="skill">CSS</span>.
                            </>,
                            <>
                                Participated in daily stand-up meetings and
                                contributed to Agile workflows.
                            </>,
                            <>
                                Gained experience with API integration and
                                database management.
                            </>,
                        ],
                        skills: [
                            "JavaScript",
                            "HTML",
                            "CSS",
                            "API Integration",
                        ],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Personal Portfolio Website",
                description: (
                    <>
                        Developed a personal portfolio website to showcase
                        projects using <span className="skill">React</span> and{" "}
                        <span className="skill">Gatsby</span>.
                    </>
                ),
                points: [
                    <>
                        Implemented responsive design and optimized for mobile
                        devices.
                    </>,
                    <>
                        Integrated a contact form using{" "}
                        <span className="skill">Node.js</span> for server-side
                        processing.
                    </>,
                ],
            },
            {
                name: "Social Media App",
                description: (
                    <>
                        Created a social media application using{" "}
                        <span className="skill">React</span> and{" "}
                        <span className="skill">Node.js</span>.
                    </>
                ),
                points: [
                    <>
                        Developed real-time chat features using{" "}
                        <span className="skill">Socket.io</span>.
                    </>,
                    <>
                        Implemented user authentication and profile management.
                    </>,
                ],
            },
        ],
        references: [
            {
                name: "Emma White",
                company: "Data Insights Corp.",
                phone: "(555) 555-5568",
            },
        ],
    },
    {
        name: "Michael Lee",
        title: "DevOps Engineer",
        phone: "(555) 555-5560",
        email: "michael.lee@example.com",
        location: "Boston, MA",
        summary: (
            <>
                DevOps engineer with hands-on experience in automating
                infrastructure using
                <span className="skill">Docker</span> and{" "}
                <span className="skill">Kubernetes</span>. Proficient in
                continuous integration and deployment pipelines.
            </>
        ),
        education: [
            {
                start: "Sep 2012",
                end: "Jun 2016",
                level: "Bachelor's Degree",
                field: "Computer Science",
                subfield: "Systems Engineering",
                school: {
                    name: "Boston University",
                    location: "Boston, MA",
                },
            },
        ],
        certifications: [
            {
                date: "Mar 2020",
                name: "Certified Kubernetes Administrator",
            },
            {
                date: "Jun 2021",
                name: "AWS Certified Solutions Architect",
            },
        ],
        skills: [
            { name: "Docker", level: "expert" },
            { name: "Kubernetes", level: "expert" },
            { name: "AWS", level: "experienced" },
            { name: "Terraform", level: "experienced" },
            { name: "CI/CD", level: "skillful" },
            "Linux",
            "Git",
            "Python",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "Korean", level: "B1" },
        ],
        links: [
            {
                url: "https://github.com/michaellee",
                prettyUrl: "github.com/michaellee",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/michael-lee",
                prettyUrl: "linkedin.com/in/michael-lee",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Cloud Solutions Inc.",
                location: "Boston, MA",
                positions: [
                    {
                        title: "DevOps Engineer",
                        start: "Aug 2020",
                        end: "Present",
                        points: [
                            <>
                                Designed and implemented CI/CD pipelines using{" "}
                                <span className="skill">Jenkins</span> and{" "}
                                <span className="skill">GitLab CI</span>.
                            </>,
                            <>
                                Automated infrastructure provisioning using{" "}
                                <span className="skill">Terraform</span> and{" "}
                                <span className="skill">
                                    AWS CloudFormation
                                </span>
                                .
                            </>,
                            <>
                                Managed container orchestration with{" "}
                                <span className="skill">Kubernetes</span>.
                            </>,
                        ],
                        skills: ["Jenkins", "AWS", "Docker", "Kubernetes"],
                    },
                ],
            },
            {
                organization: "Tech Innovations LLC",
                location: "Boston, MA",
                positions: [
                    {
                        title: "Junior DevOps Engineer",
                        start: "Jul 2018",
                        end: "Jul 2020",
                        points: [
                            <>
                                Assisted in managing cloud infrastructure on{" "}
                                <span className="skill">AWS</span>.
                            </>,
                            <>
                                Developed automation scripts using{" "}
                                <span className="skill">Python</span> and{" "}
                                <span className="skill">Bash</span>.
                            </>,
                            <>
                                Collaborated with development teams to
                                streamline deployment processes.
                            </>,
                        ],
                        skills: ["AWS", "Python", "Bash", "Git"],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Infrastructure Automation Project",
                description: (
                    <>
                        Led a project to automate infrastructure provisioning on{" "}
                        <span className="skill">AWS</span> using{" "}
                        <span className="skill">Terraform</span>.
                    </>
                ),
                points: [
                    <>Improved deployment speed by 30% through automation.</>,
                    <>Developed reusable modules for provisioning resources.</>,
                ],
            },
            {
                name: "Kubernetes Migration",
                description: (
                    <>
                        Managed the migration of legacy applications to a
                        containerized environment using{" "}
                        <span className="skill">Kubernetes</span>.
                    </>
                ),
                points: [
                    <>Designed Helm charts for application deployment.</>,
                    <>
                        Established monitoring and logging solutions using{" "}
                        <span className="skill">Prometheus</span> and{" "}
                        <span className="skill">Grafana</span>.
                    </>,
                ],
            },
        ],
        references: "Available upon request",
    },
    {
        name: "Sarah Williams",
        title: "UI/UX Designer",
        phone: "(555) 555-5561",
        email: "sarah.williams@example.com",
        location: "Los Angeles, CA",
        summary: (
            <>
                Experienced UI/UX designer with a keen eye for detail. Adept in
                using
                <span className="skill">Figma</span> and{" "}
                <span className="skill">Sketch</span> to create intuitive and
                visually appealing designs.
            </>
        ),
        education: [
            {
                start: "Sep 2013",
                end: "Jun 2017",
                level: "Bachelor's Degree",
                field: "Graphic Design",
                subfield: "User Experience Design",
                school: {
                    name: "California State University",
                    location: "Los Angeles, CA",
                },
            },
        ],
        certifications: [
            {
                date: "Feb 2019",
                name: "Certified UX Designer",
            },
            {
                date: "Oct 2020",
                name: "Google UX Design Certificate",
            },
        ],
        skills: [
            { name: "Figma", level: "expert" },
            { name: "Sketch", level: "expert" },
            { name: "Adobe XD", level: "experienced" },
            { name: "Usability Testing", level: "experienced" },
            { name: "Prototyping", level: "skillful" },
            "HTML",
            "CSS",
            "JavaScript",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "Mandarin", level: "A2" },
        ],
        links: [
            {
                url: "https://dribbble.com/sarahwilliams",
                prettyUrl: "dribbble.com/sarahwilliams",
                icon: <i className="fab fa-dribbble" />,
                label: "Dribbble",
            },
            {
                url: "https://linkedin.com/in/sarah-williams",
                prettyUrl: "linkedin.com/in/sarah-williams",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Creative Agency Inc.",
                location: "Los Angeles, CA",
                positions: [
                    {
                        title: "UI/UX Designer",
                        start: "Aug 2019",
                        end: "Present",
                        points: [
                            <>
                                Designed user-friendly interfaces for web and
                                mobile applications using{" "}
                                <span className="skill">Figma</span> and{" "}
                                <span className="skill">Sketch</span>.
                            </>,
                            <>
                                Conducted user research and usability testing to
                                inform design decisions.
                            </>,
                            <>
                                Collaborated with developers to ensure design
                                feasibility and implementation.
                            </>,
                        ],
                        skills: [
                            "Figma",
                            "Sketch",
                            "Usability Testing",
                            "HTML",
                            "CSS",
                        ],
                    },
                ],
            },
            {
                organization: "Digital Design Studio",
                location: "Los Angeles, CA",
                positions: [
                    {
                        title: "Junior UI/UX Designer",
                        start: "Jun 2017",
                        end: "Jul 2019",
                        points: [
                            <>
                                Assisted in the creation of wireframes and
                                prototypes for client projects.
                            </>,
                            <>
                                Supported the design team with graphic design
                                and layout tasks.
                            </>,
                            <>
                                Participated in brainstorming sessions and
                                contributed to creative concepts.
                            </>,
                        ],
                        skills: ["Adobe XD", "Figma", "Wireframing"],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "E-Commerce Website Redesign",
                description: (
                    <>
                        Led the redesign of a major e-commerce website to
                        improve user experience and conversion rates.
                    </>
                ),
                points: [
                    <>
                        Conducted user research and A/B testing to identify pain
                        points in the existing design.
                    </>,
                    <>
                        Implemented a new design system that enhanced the visual
                        appeal and usability of the site.
                    </>,
                ],
            },
            {
                name: "Mobile App Design",
                description: (
                    <>
                        Designed a mobile app for a local restaurant to
                        streamline online ordering and reservations.
                    </>
                ),
                points: [
                    <>
                        Created interactive prototypes to showcase the app's
                        features and user flow.
                    </>,
                    <>
                        Collaborated with the marketing team to align the app
                        design with the brand identity.
                    </>,
                ],
            },
        ],
        references: "Available upon request",
    },
    {
        name: "David Thompson",
        title: "Cloud Architect",
        phone: "(555) 555-5562",
        email: "david.thompson@example.com",
        location: "San Francisco, CA",
        summary: (
            <>
                Cloud architect with deep knowledge of{" "}
                <span className="skill">AWS</span> and
                <span className="skill">Azure</span>. Experienced in designing
                and deploying scalable cloud solutions for enterprise clients.
            </>
        ),
        education: [
            {
                start: "Sep 2010",
                end: "Jun 2014",
                level: "Bachelor's Degree",
                field: "Information Technology",
                subfield: "Cloud Computing",
                school: {
                    name: "Stanford University",
                    location: "Stanford, CA",
                },
            },
        ],
        certifications: [
            {
                date: "Apr 2019",
                name: "AWS Certified Solutions Architect - Associate",
            },
            {
                date: "Nov 2020",
                name: "Microsoft Certified: Azure Solutions Architect Expert",
            },
        ],
        skills: [
            { name: "AWS", level: "expert" },
            { name: "Azure", level: "expert" },
            { name: "Terraform", level: "experienced" },
            { name: "Kubernetes", level: "experienced" },
            { name: "Docker", level: "skillful" },
            "Cloud Security",
            "DevOps",
            "Networking",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "Spanish", level: "B2" },
        ],
        links: [
            {
                url: "https://github.com/davidthompson",
                prettyUrl: "github.com/davidthompson",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/david-thompson",
                prettyUrl: "linkedin.com/in/david-thompson",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Cloud Solutions Group",
                location: "San Francisco, CA",
                positions: [
                    {
                        title: "Cloud Architect",
                        start: "Jan 2020",
                        end: "Present",
                        points: [
                            <>
                                Designed and implemented cloud architecture
                                solutions on <span className="skill">AWS</span>{" "}
                                and <span className="skill">Azure</span>.
                            </>,
                            <>
                                Developed Infrastructure as Code (IaC) using{" "}
                                <span className="skill">Terraform</span>.
                            </>,
                            <>
                                Conducted cloud readiness assessments for
                                enterprise clients.
                            </>,
                        ],
                        skills: ["AWS", "Azure", "Terraform", "Cloud Security"],
                    },
                ],
            },
            {
                organization: "Tech Innovators Inc.",
                location: "San Francisco, CA",
                positions: [
                    {
                        title: "Cloud Engineer",
                        start: "Jul 2015",
                        end: "Dec 2019",
                        points: [
                            <>
                                Managed and optimized cloud environments using{" "}
                                <span className="skill">AWS</span>.
                            </>,
                            <>
                                Collaborated with development teams to ensure
                                seamless application deployment.
                            </>,
                            <>
                                Implemented monitoring solutions to maintain
                                system health and performance.
                            </>,
                        ],
                        skills: ["AWS", "DevOps", "Monitoring", "Networking"],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Enterprise Cloud Migration",
                description: (
                    <>
                        Led a successful migration of on-premise infrastructure
                        to <span className="skill">AWS</span>.
                    </>
                ),
                points: [
                    <>
                        Developed a comprehensive migration strategy that
                        minimized downtime.
                    </>,
                    <>
                        Trained team members on best practices for cloud
                        architecture.
                    </>,
                ],
            },
            {
                name: "Kubernetes Deployment",
                description: (
                    <>
                        Designed a Kubernetes cluster to manage containerized
                        applications for a large enterprise client.
                    </>
                ),
                points: [
                    <>
                        Implemented CI/CD pipelines for automated deployments
                        using <span className="skill">Jenkins</span>.
                    </>,
                    <>
                        Established monitoring and logging solutions using{" "}
                        <span className="skill">Prometheus</span> and{" "}
                        <span className="skill">Grafana</span>.
                    </>,
                ],
            },
        ],
        references: "Available upon request",
    },
    {
        name: "Jessica Brown",
        title: "Mobile App Developer",
        phone: "(555) 555-5563",
        email: "jessica.brown@example.com",
        location: "Miami, FL",
        summary: (
            <>
                Mobile app developer specializing in{" "}
                <span className="skill">React Native</span> and{" "}
                <span className="skill">Swift</span>. Focused on creating
                high-performance mobile applications with a great user
                experience.
            </>
        ),
        education: [
            {
                start: "Sep 2014",
                end: "Jun 2018",
                level: "Bachelor's Degree",
                field: "Computer Science",
                subfield: "Mobile Development",
                school: {
                    name: "University of Miami",
                    location: "Miami, FL",
                },
            },
        ],
        certifications: [
            {
                date: "Mar 2019",
                name: "Certified Mobile Application Developer",
            },
            {
                date: "Dec 2021",
                name: "Google Associate Android Developer",
            },
        ],
        skills: [
            { name: "React Native", level: "expert" },
            { name: "Swift", level: "experienced" },
            { name: "Java", level: "experienced" },
            { name: "Firebase", level: "skillful" },
            "HTML",
            "CSS",
            "Git",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "Portuguese", level: "B1" },
        ],
        links: [
            {
                url: "https://github.com/jessicabrown",
                prettyUrl: "github.com/jessicabrown",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/jessica-brown",
                prettyUrl: "linkedin.com/in/jessica-brown",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Mobile Innovations LLC",
                location: "Miami, FL",
                positions: [
                    {
                        title: "Mobile App Developer",
                        start: "Jul 2018",
                        end: "Present",
                        points: [
                            <>
                                Developed cross-platform mobile applications
                                using{" "}
                                <span className="skill">React Native</span>.
                            </>,
                            <>
                                Collaborated with designers to create intuitive
                                user interfaces.
                            </>,
                            <>
                                Implemented backend services using{" "}
                                <span className="skill">Firebase</span> for
                                real-time data management.
                            </>,
                        ],
                        skills: ["React Native", "Firebase", "JavaScript"],
                    },
                ],
            },
            {
                organization: "Tech Solutions Inc.",
                location: "Miami, FL",
                positions: [
                    {
                        title: "Junior Mobile Developer",
                        start: "Jun 2016",
                        end: "Jun 2018",
                        points: [
                            <>
                                Assisted in the development of native Android
                                applications using{" "}
                                <span className="skill">Java</span>.
                            </>,
                            <>
                                Participated in user testing and provided
                                feedback to improve app functionality.
                            </>,
                            <>
                                Contributed to the integration of RESTful APIs
                                for backend connectivity.
                            </>,
                        ],
                        skills: ["Java", "Android Development", "RESTful APIs"],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Fitness Tracker App",
                description: (
                    <>
                        Developed a fitness tracking application using{" "}
                        <span className="skill">React Native</span> that allows
                        users to log their workouts and monitor progress.
                    </>
                ),
                points: [
                    <>
                        Implemented features for workout tracking, user
                        profiles, and data visualization.
                    </>,
                    <>
                        Integrated third-party APIs for nutrition and health
                        data.
                    </>,
                ],
            },
            {
                name: "Travel Planner App",
                description: (
                    <>
                        Created a mobile app to help users plan their trips with
                        itinerary management and local recommendations.
                    </>
                ),
                points: [
                    <>
                        Designed a user-friendly interface and implemented
                        offline capabilities.
                    </>,
                    <>
                        Collaborated with a team to enhance user experience
                        through iterative testing.
                    </>,
                ],
            },
        ],
        references: "Available upon request",
    },
    {
        name: "Chris Miller",
        title: "Data Scientist",
        phone: "(555) 555-5564",
        email: "chris.miller@example.com",
        location: "New York, NY",
        summary: (
            <>
                Data scientist with expertise in statistical analysis and
                machine learning using
                <span className="skill">Python</span> and{" "}
                <span className="skill">TensorFlow</span>. Passionate about
                uncovering insights from data to drive business decisions.
            </>
        ),
        education: [
            {
                start: "Sep 2012",
                end: "Jun 2016",
                level: "Bachelor's Degree",
                field: "Mathematics",
                subfield: "Data Science",
                school: {
                    name: "Columbia University",
                    location: "New York, NY",
                },
            },
        ],
        certifications: [
            {
                date: "May 2020",
                name: "Certified Data Scientist",
            },
            {
                date: "Jan 2022",
                name: "Google Professional Data Engineer",
            },
        ],
        skills: [
            { name: "Python", level: "expert" },
            { name: "R", level: "experienced" },
            { name: "Machine Learning", level: "expert" },
            { name: "TensorFlow", level: "experienced" },
            { name: "Data Visualization", level: "skillful" },
            "SQL",
            "Pandas",
            "NumPy",
        ],
        languages: [
            { name: "English", level: "Native speaker" },
            { name: "French", level: "B2" },
        ],
        links: [
            {
                url: "https://github.com/chrismiller",
                prettyUrl: "github.com/chrismiller",
                icon: <i className="fab fa-github" />,
                label: "GitHub",
            },
            {
                url: "https://linkedin.com/in/chris-miller",
                prettyUrl: "linkedin.com/in/chris-miller",
                icon: <i className="fab fa-linkedin" />,
                label: "LinkedIn",
            },
        ],
        experience: [
            {
                organization: "Data Insights Corp.",
                location: "New York, NY",
                positions: [
                    {
                        title: "Data Scientist",
                        start: "Aug 2020",
                        end: "Present",
                        points: [
                            <>
                                Developed predictive models using{" "}
                                <span className="skill">Python</span> and{" "}
                                <span className="skill">scikit-learn</span> to
                                forecast sales trends.
                            </>,
                            <>
                                Conducted data analysis and visualization to
                                present findings to stakeholders.
                            </>,
                            <>
                                Collaborated with cross-functional teams to
                                implement data-driven solutions.
                            </>,
                        ],
                        skills: [
                            "Python",
                            "Machine Learning",
                            "Data Visualization",
                            "SQL",
                        ],
                    },
                ],
            },
            {
                organization: "Tech Analytics Group",
                location: "New York, NY",
                positions: [
                    {
                        title: "Junior Data Analyst",
                        start: "Jun 2016",
                        end: "Jul 2020",
                        points: [
                            <>
                                Analyzed large datasets to identify trends and
                                patterns using <span className="skill">R</span>.
                            </>,
                            <>
                                Assisted in the development of dashboards for
                                tracking key performance indicators.
                            </>,
                            <>
                                Worked closely with data engineers to improve
                                data collection and storage processes.
                            </>,
                        ],
                        skills: [
                            "R",
                            "Data Analysis",
                            "SQL",
                            "Data Visualization",
                        ],
                    },
                ],
            },
        ],
        notableProjects: [
            {
                name: "Customer Churn Prediction",
                description: (
                    <>
                        Created a machine learning model to predict customer
                        churn using <span className="skill">Python</span> and{" "}
                        <span className="skill">TensorFlow</span>.
                    </>
                ),
                points: [
                    <>
                        Improved customer retention strategies based on model
                        insights.
                    </>,
                    <>
                        Presented findings to executive leadership, influencing
                        company policy.
                    </>,
                ],
            },
            {
                name: "Sales Forecasting Tool",
                description: (
                    <>
                        Developed a tool for forecasting sales using time series
                        analysis and <span className="skill">R</span>.
                    </>
                ),
                points: [
                    <>
                        Automated data retrieval processes to streamline
                        forecasting.
                    </>,
                    <>
                        Enhanced accuracy of predictions by implementing
                        advanced statistical techniques.
                    </>,
                ],
            },
        ],
        references: "Available upon request",
    },
];

export default dummy_resume_data;
